fieldLayouts:
  24ead58a-2102-4f86-a7d5-f570d8265797:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6efcc7d1-17e7-4880-9107-104c51a1a031
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Header
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4c8d2d62-5025-479a-938e-85b4d983e83e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 6a125d5b-d0f4-448b-ad2c-982976a457f7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a6385c4-4013-4687-90ad-1feeafd273c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 789e0a59-7426-4a3a-96a3-9b3f34ed958f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Teaser
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 2ef40c1a-fa32-405d-afc8-284aa0281b0a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 4
handle: services
hasTitleField: true
name: Services
section: a3bde867-0359-4c2e-9697-972f4b42eb36
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
