fieldLayouts:
  e008d88b-64cc-45e1-b48c-c5a8eb49a0ba:
    tabs:
      -
        elements:
          -
            fieldUid: 8c37f80e-7983-4052-838b-8df59e75b108
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Naam
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a387e404-a1ae-40a2-be5f-917800e7d0f2
            instructions: ''
            label: Functie
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c8d2d62-5025-479a-938e-85b4d983e83e
            instructions: ''
            label: Beschrijving
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eff4bf4c-f34e-4e11-944c-c132eb404694
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 99eb80f8-ad39-4772-9111-899d244fa56b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: team
hasTitleField: true
name: Team
section: 706804fb-3dd4-459c-bad8-561b62654153
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
