handle: mainNav
instructions: ''
maxNodes: ''
name: Hoofdmenu
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - 'single:c678556d-4b65-4ad5-9b3d-5a976756af64'
      - 'section:c22317fe-ede2-49d6-9c1c-9dd4ba995764'
      - 'single:4c9b0d1e-c875-47bf-9bc4-4742167919c7'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  9c0e7bfb-10c6-4875-8c5f-03da5842320b: null
sortOrder: 1
structure:
  maxLevels: null
  uid: 8f1267c3-2b98-4e26-8a39-fa34b3c68fdc
