childBlocks: null
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
fieldLayouts:
  3b831667-9987-4593-980b-5d953c3ac75d:
    tabs:
      -
        elements:
          -
            fieldUid: 8c37f80e-7983-4052-838b-8df59e75b108 # Afbeelding
            instructions: ''
            label: Gallerij
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blockGallery
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Gallerij
sortOrder: 9
topLevel: false
