childBlocks: ''
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
fieldLayouts:
  45e5ad46-1830-4ea4-9799-f0f140f41d57:
    tabs:
      -
        elements:
          -
            fieldUid: 54cd2e2b-47b8-4eee-a066-14d594e4466e # Quote
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blockQuote
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Quote
sortOrder: 12
topLevel: false
