childBlocks:
  - blockImage
  - blockForm
  - blockIconText
  - blockQuote
  - blockRedactor
  - blockVideo
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
handle: moduleOneAndTwoThirds
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: '1/3 - 2/3'
sortOrder: 5
topLevel: true
