childBlocks:
  - blockImage
  - blockIconText
  - blockQuote
  - blockRedactor
  - blockVideo
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Builder
handle: moduleOneThirds
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: '1/3 - 1/3 - 1/3'
sortOrder: 4
topLevel: true
