contentColumnType: string
fieldGroup: d0393e73-f781-4174-9020-2f7649b53d09
handle: blockOverview
instructions: ''
name: Overzicht
searchable: false
settings:
  allowMultiple: ''
  whitelistedSections:
    - '6'
    - '5'
translationKeyFormat: null
translationMethod: none
type: charliedev\sectionfield\fields\SectionField
