contentColumnType: string
fieldGroup: d0393e73-f781-4174-9020-2f7649b53d09
handle: blockTeasers
instructions: ''
name: Teasers
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:c22317fe-ede2-49d6-9c1c-9dd4ba995764'
    - 'section:a3bde867-0359-4c2e-9697-972f4b42eb36'
    - 'section:706804fb-3dd4-459c-bad8-561b62654153'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
