contentColumnType: string
fieldGroup: d0393e73-f781-4174-9020-2f7649b53d09
handle: blockIcon
instructions: ''
name: Icoon
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - compressed
    - image
    - json
  defaultUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  defaultUploadLocationSubpath: /icons
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
