contentColumnType: text
fieldGroup: 0dae9c2c-8aab-44a0-8c73-d6f5c596c5dd
handle: bodyScript
instructions: ''
name: 'Body Script'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
