enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  9c0e7bfb-10c6-4875-8c5f-03da5842320b:
    enabledByDefault: true
    hasUrls: true
    template: _resolvers/page
    uriFormat: '{parent.uri ?? ''services''}/{slug}'
structure:
  maxLevels: null
  uid: cf361429-50b8-413a-be7b-f8abc2d0da49
type: structure
